title: Site
sections:
  pages:
    type: pages
    headline: Seiten
    image: icon

  site_info:
    type: fields
    fields:
      description:
        label: Seitenbeschreibung
        type: text
        help: Vorschautext (z.B in Suchmaschienen)

      keywords:
        label: Keywords
        type: text
        help: Schlagwärter zur Suchmaschinen optimierung. Durch Komma trennen!
